### ISSUE TITLE
Opening world list with worlds generated using non-modded world type freezes the game

### ISSUE THREAD

**Issue by pkstDev** [Amb0s/retro-world-gen#1]
It simply throws an NPE and results a dirt screen
```log
[13:04:49] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.7.6 with Fabric Loader 0.14.6-babric.1
[13:04:49] [main/INFO] (FabricLoader/Mappings) Mappings not present!
[13:04:49] [main/INFO] (FabricLoader) Loading 19 mods:
	- btamodlist 1.1.0
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabricloader 0.14.6-babric.1
	- invpausing 1.0.0
	- java 17
	- minecraft 1.7.6
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- retroworldgen 2.1.0
	- vanillafixes 2.0.0
[13:04:49] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/G:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:04:50] [main] 1419 Translation Keys
[13:04:51] [main] 390 recipes
[13:04:51] [main] 22 Achievements
[13:04:51] [main] Setting user: Peakstep, token:<ACCESS TOKEN>:<PROFILE ID>
[13:04:51] [Minecraft main thread] Java Version: 17.0.3
[13:04:52] [Minecraft main thread] Skipping bad option: lastServer:
[13:04:52] [Minecraft main thread] Skipping bad option: shaderpack:
[13:04:52] [Minecraft main thread] Skipping bad option: selectedController:
[13:04:52] [Minecraft main thread] 4.6.0 NVIDIA 456.71
[13:04:52] [Minecraft main thread] NVIDIA Corporation
[13:04:52] [Minecraft main thread] GeForce GTX 1060 3GB/PCIe/SSE2
[13:04:52] [Minecraft main thread] Testing Capabilities...
[13:04:52] [Minecraft main thread] Shaders Activated!
[13:04:52] [Minecraft main thread] Drawing Loading Screen...
[13:04:52] [Minecraft main thread] Initizalizing Input
[13:04:52] [Minecraft main thread] Creating Mouse & Keyboard
[13:04:52] [Minecraft main thread] Initizalizing Controllers
[13:04:52] [Minecraft main thread] ControllerEnvironment: net.java.games.input.DefaultControllerEnvironment@66f3ff91
Jul 26, 2022 1:04:52 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 11
Jul 26, 2022 1:04:52 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Jul 26, 2022 1:04:52 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
[13:04:52] [Minecraft main thread] 5 Devices
[13:04:52] [Minecraft main thread] Available Devices: 
[13:04:52] [Minecraft main thread] HID Keyboard Device (Keyboard)
[13:04:52] [Minecraft main thread] HID-compliant mouse (Mouse)
[13:04:52] [Minecraft main thread] A1 (Unknown)
[13:04:52] [Minecraft main thread] Dell KB216 Wired Keyboard (Unknown)
[13:04:52] [Minecraft main thread] Dell KB216 Wired Keyboard (Unknown)
[13:04:52] [Minecraft main thread] Saved Controller: 
[13:04:52] [Minecraft main thread] Input Done!
[13:04:52] [Minecraft main thread] Setting up OpenGL Values...
[13:04:52] [Minecraft main thread] 
[13:04:52] [Minecraft main thread] Starting up SoundSystem...
[13:04:53] [Thread-5] Initializing LWJGL OpenAL
[13:04:53] [Thread-5]     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:04:53] [Thread-5] OpenAL initialized.
[13:04:53] [Minecraft main thread] 
[13:04:53] [Minecraft main thread] Initializing Dynamic Textures...
[13:04:53] [Minecraft main thread] Resolution: Terrain: 16 Items: 16
[13:04:53] [Minecraft main thread] Using Custom Still Water Animation
[13:04:53] [Minecraft main thread] Frame Count: 32
[13:04:53] [Minecraft main thread] Using Custom Flowing Water Animation
[13:04:53] [Minecraft main thread] Frame Count: 64
[13:04:53] [Minecraft main thread] Using Custom Still Lava Animation
[13:04:53] [Minecraft main thread] Frame Count: 20
[13:04:53] [Minecraft main thread] Using Custom Flowing Lava Animation
[13:04:53] [Minecraft main thread] Frame Count: 32
[13:04:53] [Minecraft main thread] Using Generated Portal Animation
[13:04:53] [Minecraft main thread] Initializing Renderer...
[13:04:53] [Minecraft main thread] Starting Resource Download Thread...
[13:04:55] [Resource Download] Downloading sounds...
[13:04:56] [Minecraft main thread] ModLoader is disabled!
[13:04:57] [Minecraft main thread] Expanding buffer to 7749120
[13:04:57] [Resource Download] Installed 223 Sound Files!
[13:05:08] [Minecraft main thread] logged in with session name: Peakstep
[13:05:09] [GetSkinUrlThread 0] Loading Skin for Player Peakstep...
[13:05:09] [GetSkinUrlThread 0] Skin URL: http://textures.minecraft.net/texture/356eb08d8706da8233d56a4ed68d50e53af5c2dc61248a2dee7de6f38e1fa603
[13:05:09] [GetSkinUrlThread 0] Cape URL: http://textures.minecraft.net/texture/2340c0e03dd24a11b15a8b33c2a7e9e32abb2051b2481d0ba7defd635ca7a933
[13:05:19] [Minecraft main thread] java.lang.NullPointerException: Cannot read field "languageKey" because "net.minecraft.src.WorldType.worldTypes[net.minecraft.src.WorldInfo.getWorldType(int)]" is null
[13:05:19] [Minecraft main thread] 	at net.minecraft.src.GuiWorldSlot.drawSlot(GuiWorldSlot.java:81)
[13:05:19] [Minecraft main thread] 	at net.minecraft.src.GuiSlot.drawScreen(GuiSlot.java:253)
[13:05:19] [Minecraft main thread] 	at net.minecraft.src.GuiSelectWorld.drawScreen(GuiSelectWorld.java:154)
[13:05:19] [Minecraft main thread] 	at net.minecraft.src.EntityRenderer.updateCameraAndRender(EntityRenderer.java:536)
[13:05:19] [Minecraft main thread] 	at net.minecraft.client.Minecraft.run(Minecraft.java:661)
[13:05:19] [Minecraft main thread] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Amb0s** [comment]
Fixed. Thanks for your report!
